name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: python-base-ubuntu
            from: ubuntu:24.04@sha256:cd1dba651b3080c3686ecf4e3c4220f026b521fb76978881737d24f200828b2b
          - name: ubuntu-cloud-archive
            image-name: python-base-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2024.1@sha256:35b7917ca0fc2c7b125d1ed9cef06d2b231ff73a782d69d40956ca2909e0f343
          - name: ubuntu-cloud-archive-legacy
            image-name: python-base
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2024.1@sha256:35b7917ca0fc2c7b125d1ed9cef06d2b231ff73a782d69d40956ca2909e0f343
          - name: debian
            image-name: python-base-debian
            from: debian:bookworm
          - name: rockylinux
            image-name: python-base-rockylinux
            from: rockylinux:9
          - name: almalinux
            image-name: python-base-almalinux
            from: almalinux:9
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: ${{ matrix.image-name }}
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
