name: build

on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - stable/**

jobs:
  image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: ubuntu
            image-name: python-base-ubuntu
            from: ubuntu:24.04@sha256:25f37267ed09741eb764578a14df49a0c0bede9755fc8fc18a51b101985b924c
          - name: ubuntu-cloud-archive
            image-name: python-base-ubuntu-cloud-archive
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2024.2@sha256:8c123d93f28e98b761945c7f38f6364adaa41a1eaf56d2084aa46a58b96cd519
          - name: ubuntu-cloud-archive-legacy
            image-name: python-base
            from: ghcr.io/vexxhost/ubuntu-cloud-archive:2024.2@sha256:8c123d93f28e98b761945c7f38f6364adaa41a1eaf56d2084aa46a58b96cd519
          - name: debian
            image-name: python-base-debian
            from: debian:trixie@sha256:2c91e484d93f0830a7e05a2b9d92a7b102be7cab562198b984a84fdbc7806d91
          - name: rockylinux
            image-name: python-base-rockylinux
            from: rockylinux:9@sha256:d7be1c094cc5845ee815d4632fe377514ee6ebcf8efaed6892889657e5ddaaa6
          - name: almalinux
            image-name: python-base-almalinux
            from: almalinux:9@sha256:4e5f333756e39943fe66e3b55ee4c303805eebd7c6da372f07f2418f79b23d87
    permissions:
      contents: read
      id-token: write
      packages: write
      pull-requests: write
    steps:
      - uses: vexxhost/docker-atmosphere/.github/actions/build-image@main
        with:
          image-name: ${{ matrix.image-name }}
          build-args: FROM=${{ matrix.from }}
          push: ${{ github.event_name != 'pull_request' }}
